"""Source dicts -> biblatex .bib text, and debounced background sync to configured files."""

import re
import threading
import time
from pathlib import Path

import bibtexparser
from bibtexparser.library import Library
from bibtexparser.model import Entry, Field
from pylatexenc.latexencode import UnicodeToLatexEncoder

import store
from fields import FIELDS

HEADER = "% generated by sources, edits will be overwritten\n\n"
DEBOUNCE = 5  # seconds after the last change
INTERVAL = 15 * 60  # full resync, picks up edits made outside the app

_RAW_TYPES = {"uri", "verbatim"}  # written as-is (urls, doi, file paths)
_FIELD_NAME = re.compile(r"^[a-z][a-z0-9_\-:.]*$")

_latex = UnicodeToLatexEncoder(
    unknown_char_policy="keep", replacement_latex_protection="braces-after-macro"
)


def _enc(s: str) -> str:
    return _latex.unicode_to_latex(s)


def _protect(s: str) -> str:
    """Brace a name/list item that bibtex would otherwise split."""
    return f"{{{s}}}" if re.search(r",|\band\b", s, re.I) else s


def _name(n: dict) -> str:
    family = " ".join(p for p in (n.get("prefix"), n.get("family")) if p)
    given, suffix = n.get("given", ""), n.get("suffix", "")
    if not given and not suffix:
        # corporate / single-part name: keep it one unit
        return f"{{{_enc(family)}}}" if " " in family else _protect(_enc(family))
    parts = [_protect(_enc(family))]
    if suffix:
        parts.append(_protect(_enc(suffix)))
    parts.append(_protect(_enc(given)))
    return ", ".join(parts)


def _value(name: str, value) -> str:
    t = FIELDS[name]["type"]
    if t == "name":
        return " and ".join(_name(n) for n in value)
    if t == "list":
        return " and ".join(_protect(_enc(v)) for v in value)
    if t in _RAW_TYPES:
        return str(value)
    return _enc(str(value))


def _entry(s: dict) -> Entry:
    fields = []
    if s.get("title"):
        fields.append(Field("title", _enc(s["title"])))
    for name, value in s.items():
        if name in FIELDS:
            fields.append(Field(name, _value(name, value)))
    for name, value in (s.get("extra") or {}).items():
        name = name.lower()
        if name != "entrytype" and name not in FIELDS and _FIELD_NAME.match(name):
            fields.append(Field(name, _enc(value)))
    return Entry(s["entrytype"], s["key"], fields)


def render(sources: list[dict]) -> str:
    lib = Library([_entry(s) for s in sorted(sources, key=lambda s: s["key"])])
    return HEADER + bibtexparser.write_string(lib).strip() + "\n"


def _write(path: str, text: str) -> None:
    p = Path(path)
    if not p.is_absolute():
        raise ValueError("not an absolute path")
    if p.suffix != ".bib":
        raise ValueError("must end in .bib")
    if not p.parent.is_dir():
        raise ValueError(f"{p.parent} does not exist")
    try:
        current = p.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if current == text:
        return
    if current and not current.startswith(HEADER.strip()):
        raise ValueError("file exists and was not generated by sources")
    tmp = p.with_name(f".{p.name}.tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(p)


# path -> error message, or None if the last sync succeeded
status: dict[str, str | None] = {}
_lock = threading.Lock()
_timer: threading.Timer | None = None


def sync() -> None:
    """Write all configured .bib files. Unchanged files are not touched."""
    with _lock:
        paths = store.get_bib_paths()
        if not paths:
            status.clear()
            return
        try:
            text = render(store.list_sources())
        except Exception as e:  # noqa: BLE001 - report instead of crashing the thread
            status.clear()
            status.update({p: str(e) for p in paths})
            return
        result = {}
        for p in paths:
            try:
                _write(p, text)
                result[p] = None
            except (OSError, ValueError) as e:
                result[p] = str(e)
        status.clear()
        status.update(result)


def schedule() -> None:
    """Debounced sync: runs DEBOUNCE seconds after the last call."""
    global _timer
    if _timer:
        _timer.cancel()
    _timer = threading.Timer(DEBOUNCE, sync)
    _timer.daemon = True
    _timer.start()


def start() -> None:
    """Sync now, then periodically in a daemon thread."""
    def loop():
        while True:
            sync()
            time.sleep(INTERVAL)

    threading.Thread(target=loop, daemon=True).start()
